#!/bin/bash

# requires bash 4.2 or later

if [[ -v OPENSHIFT_RHSADEMO_USER_PASSWORD_DEFAULT ]] ; then
	echo "--> Using RHSADEMO password for openshift"
	OPENSHIFT_PRIMARY_USER_PASSWORD_DEFAULT=$OPENSHIFT_RHSADEMO_USER_PASSWORD_DEFAULT
else
	[[ ! -v OPENSHIFT_PRIMARY_USER_PASSWORD_DEFAULT ]] && echo "Please set OPENSHIFT_PRIMARY_USER_PASSWORD_DEFAULT to your openshift password" && exit 1
fi

REDHAT_SUBSCRIPTION_USER=${REDHAT_SUBSCRIPTION_USER_MEPLEY:-${REDHAT_SUBSCRIPTION_USER_DEFAULT}}
: ${REDHAT_SUBSCRIPTION_USER:?Please set REDHAT_SUBSCRIPTION_USER_DEFAULT}
REDHAT_SUBSCRIPTION_USER_PASSWORD=${REDHAT_SUBSCRIPTION_USER_MEPLEY_PASSWORD:-${REDHAT_SUBSCRIPTION_USER_DEFAULT_PASSWORD}}
: ${REDHAT_SUBSCRIPTION_USER_PASSWORD:?Please set REDHAT_SUBSCRIPTION_USER_DEFAULT_PASSWORD}
REDHAT_SUBSCRIPTION_USER_POOL_ID=${REDHAT_SUBSCRIPTION_USER_MEPLEY_POOL_ID:-${REDHAT_SUBSCRIPTION_USER_DEFAULT_POOL_ID}}
: ${REDHAT_SUBSCRIPTION_USER_POOL_ID:?Please set REDHAT_SUBSCRIPTION_USER_DEFAULT_POOL_ID}


OPENSHIFT_DOMAIN_DEFAULT=rhsademo.net
OPENSHIFT_DOMAIN=${OPENSHIFT_DOMAIN_DEFAULT}

OPENSHIFT_PRIMARY_MASTER_DEFAULT=master.${OPENSHIFT_DOMAIN_DEFAULT}
OPENSHIFT_PRIMARY_MASTER=$OPENSHIFT_PRIMARY_MASTER_DEFAULT

OPENSHIFT_PRIMARY_APPS_DEFAULT=apps.${OPENSHIFT_DOMAIN_DEFAULT}
OPENSHIFT_PRIMARY_APPS=${OPENSHIFT_PRIMARY_APPS_DEFAULT}

OPENSHIFT_PRIMARY_USER_DEFAULT=mepley
OPENSHIFT_PRIMARY_USER=${OPENSHIFT_PRIMARY_USER_DEFAULT}
OPENSHIFT_PRIMARY_USER_PASSWORD=${OPENSHIFT_PRIMARY_USER_PASSWORD_DEFAULT}
OPENSHIFT_PRIMARY_PROJECT_AMQ_DEFAULT=fuse-amq
OPENSHIFT_PRIMARY_PROJECT_DEVSPACE_DEFAULT=devspace
OPENSHIFT_PRIMARY_PROJECT_UTIL_DEFAULT=util
OPENSHIFT_PRIMARY_PROJECT_DEFAULT=${OPENSHIFT_PRIMARY_PROJECT_UTIL_DEFAULT}
OPENSHIFT_PRIMARY_PROJECT=${OPENSHIFT_PRIMARY_PROJECT_DEFAULT}

OPENSHIFT_APPLICATION_NAME_RHEL_UTIL_DEFAULT=rhel
OPENSHIFT_APPLICATION_NAME_DEFAULT=${OPENSHIFT_APPLICATION_NAME_RHEL_UTIL_DEFAULT}
OPENSHIFT_APPLICATION_NAME=${OPENSHIFT_APPLICATION_NAME_DEFAULT}

echo "Configuration_______________________________________________"
echo "REDHAT_SUBSCRIPTION_USER                      = ${REDHAT_SUBSCRIPTION_USER}"
echo "REDHAT_SUBSCRIPTION_USER_PASSWORD             = `echo ${REDHAT_SUBSCRIPTION_USER_PASSWORD} | md5sum` (obfuscated) "
echo "REDHAT_SUBSCRIPTION_USER_POOL_ID              = ${REDHAT_SUBSCRIPTION_USER_POOL_ID}"
echo "OPENSHIFT_DOMAIN_DEFAULT                      = ${OPENSHIFT_DOMAIN_DEFAULT}"
echo "OPENSHIFT_DOMAIN                              = ${OPENSHIFT_DOMAIN}"
echo "OPENSHIFT_PRIMARY_MASTER_DEFAULT              = ${OPENSHIFT_PRIMARY_MASTER_DEFAULT}"
echo "OPENSHIFT_PRIMARY_MASTER                      = ${OPENSHIFT_PRIMARY_MASTER}"
echo "OPENSHIFT_PRIMARY_APPS_DEFAULT                = ${OPENSHIFT_PRIMARY_APPS_DEFAULT}"
echo "OPENSHIFT_PRIMARY_APPS                        = ${OPENSHIFT_PRIMARY_APPS}"
echo "OPENSHIFT_PRIMARY_USER_DEFAULT                = ${OPENSHIFT_PRIMARY_USER_DEFAULT}"
echo "OPENSHIFT_PRIMARY_USER                        = ${OPENSHIFT_PRIMARY_USER}"
echo "OPENSHIFT_PRIMARY_USER_PASSWORD_DEFAULT       = `echo ${OPENSHIFT_PRIMARY_USER_PASSWORD_DEFAULT} | md5sum` (obfuscated)"
echo "OPENSHIFT_PRIMARY_USER_PASSWORD               = `echo ${OPENSHIFT_PRIMARY_USER_PASSWORD} | md5sum` (obfuscated)"
echo "OPENSHIFT_PRIMARY_PROJECT_UTIL_DEFAULT        = ${OPENSHIFT_PRIMARY_PROJECT_UTIL_DEFAULT}"
echo "OPENSHIFT_PRIMARY_PROJECT_DEFAULT             = ${OPENSHIFT_PRIMARY_PROJECT_DEFAULT}"
echo "OPENSHIFT_PRIMARY_PROJECT                     = ${OPENSHIFT_PRIMARY_PROJECT}"
echo "OPENSHIFT_APPLICATION_NAME_RHEL_UTIL_DEFAULT  = ${OPENSHIFT_APPLICATION_NAME_RHEL_UTIL_DEFAULT}"
echo "OPENSHIFT_APPLICATION_NAME_DEVSPACE_DEFAULT   = ${OPENSHIFT_APPLICATION_NAME_DEVSPACE_DEFAULT}"
echo "OPENSHIFT_APPLICATION_NAME_DEFAULT            = ${OPENSHIFT_APPLICATION_NAME_DEFAULT}"
echo "OPENSHIFT_APPLICATION_NAME                    = ${OPENSHIFT_APPLICATION_NAME}"
echo "____________________________________________________________"


